### ISSUE TITLE
scantailor-cli cuts in image if image contains horizontal lines

### ISSUE THREAD

**Issue by clarkk** [scantailor/scantailor#106]
Scantailor version 0.9.11 (build from latest commit)

Source images
A: http://share.pho.to/6URSL/9y/original
B: http://share.pho.to/6UMbc/py/original

Images with areas with horizontal lines are cutted out

These two source .png files result in different outputs depending on the syntax (deskew)

In some conditions A is cutted in the part with horizontal lines and in some conditions B is cutted in the part with horizontal lines

<b>scantailor-cli --layout=1 --color-mode=black_and_white --despeckle=normal</b>
![1](https://cloud.githubusercontent.com/assets/1913916/3711732/03475a6a-14e7-11e4-98fa-c45bd6ae5490.png)

<b>scantailor-cli --layout=1 --color-mode=black_and_white --despeckle=normal --deskew=manual</b>
![2](https://cloud.githubusercontent.com/assets/1913916/3711733/0c19ace2-14e7-11e4-8d2c-f75298c4984e.png)

<b>scantailor-cli --layout=1 --color-mode=black_and_white --despeckle=normal --deskew=auto</b>
This syntax should give same output as the first syntax because deskew is set to auto by default
![3](https://cloud.githubusercontent.com/assets/1913916/3711734/133407de-14e7-11e4-83f7-8dbaf212c542.png)

**Comment by atla5** [comment]
see issue #142.
