### ISSUE TITLE
Cuts out parts with horizontal lines

### ISSUE THREAD

**Issue by clarkk** [scantailor/scantailor#137]
Scantailor-cli cuts out parts with horizontal lines

<b>scantailor-cli --layout=1 --color-mode=black_and_white --despeckle=normal pdf/out.png /pdf</b>

The input file is in 300 dpi, but same output with input file in 600 dpi

Input:
300 dpi http://share.pho.to/8rnfx/aj/original
600 dpi http://share.pho.to/8rnro/ey/original

Output
300 dpi http://share.pho.to/8rngs/6k/original

**Comment by atla5** [comment]
see issue #142
