### ISSUE TITLE
Cannot batch automatic deskew all pages

### ISSUE THREAD

**Issue by hurzl** [scantailor/scantailor#154]
If I do "apply to all pages", the actual detected rotation angle of the current page is applied to all pages

**Comment by ospalh** [comment]
If you set/change the angle and then do “apply to all pages” when deskew is sat to manual that manually set angle is applied to all pages.
Normally, the angle is detected for each page individually when you run that step for all pages. No need to “apply to all pages”

**Comment by hurzl** [comment]
When I have to correct it, I have to "apply top all pages"

**Comment by ospalh** [comment]
Well, yes. When you set it manually, and then “apply (manual deskew) to all pages”, all pages have a manually set deskew angle.
I don’t see where the problem is.

**Comment by hurzl** [comment]
If after I have set it manually I want to get automatic angles, I can't do that

**Comment by ospalh** [comment]
Yes you can. Just click the “Automatic” button, apply to all, go to first page and click the play button in the top left list next to deskew.

**Comment by hurzl** [comment]
It seems to work now, I don't know what I did wrong, sorry.
