### ISSUE TITLE
Qt5

### ISSUE THREAD

**Issue by ospalh** [scantailor/scantailor#164]
Please go over to Qt5
One reason:
I have problems telling the difference between the very light gray standard background color and the white paper, and so can’t move the content box to the edge of the paper.
And i [can’t change the color scheme](https://superuser.com/questions/948184/make-qt4-apps-use-the-kde5-color-scheme) of Qt4 apps.

**Comment by glixx** [comment]
It's time for Qt5.

**Comment by atla5** [comment]
debating between including this as part of release 1.0.0 and whatever release would follow after that.

thoughts?

**Comment by atla5** [comment]
see #121.
