### ISSUE TITLE
Build fails: undefined reference to `boost::unit_test::ut_detail::normalize_test_case_name(boost::unit_test::basic_cstring<char const>)

### ISSUE THREAD

**Issue by Wikinaut** [scantailor/scantailor#166]
```
[ 92%] Linking CXX executable spfit_tests
CMakeFiles/spfit_tests.dir/TestSqDistApproximant.cpp.o: In function `boost::unit_test::make_test_case(boost::unit_test::callback0<boost::unit_test::ut_detail::unused> const&, boost::unit_test::basic_cstring<char const>)':
TestSqDistApproximant.cpp:(.text._ZN5boost9unit_test14make_test_caseERKNS0_9callback0INS0_9ut_detail6unusedEEENS0_13basic_cstringIKcEE[_ZN5boost9unit_test14make_test_caseERKNS0_9callback0INS0_9ut_detail6unusedEEENS0_13basic_cstringIKcEE]+0x13): undefined reference to `boost::unit_test::ut_detail::normalize_test_case_name(boost::unit_test::basic_cstring<char const>)'
collect2: error: ld returned 1 exit status
math/spfit/tests/CMakeFiles/spfit_tests.dir/build.make:128: die Regel für Ziel „math/spfit/tests/spfit_tests“ scheiterte
make[2]: *** [math/spfit/tests/spfit_tests] Fehler 1
CMakeFiles/Makefile2:527: die Regel für Ziel „math/spfit/tests/CMakeFiles/spfit_tests.dir/all“ scheiterte
make[1]: *** [math/spfit/tests/CMakeFiles/spfit_tests.dir/all] Fehler 2
Makefile:160: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2
```

**Comment by Wikinaut** [comment]
doublure of issue #165 . 

(#166 reported while trying to build on openSUSE Tumbleweed)

Please can this be fixed soon, thanks in advance.

**Comment by danstender** [comment]
Quick fix: add the line
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_GLIBCXX_USE_CXX11_ABI=0")
to the top of scantailor/CMakeLists.txt

**Comment by Wikinaut** [comment]
I did so, but get the same message.

make clean
cmake .
make



```
[ 93%] Linking CXX executable spfit_tests
CMakeFiles/spfit_tests.dir/TestSqDistApproximant.cpp.o: In function `boost::unit_test::make_test_case(boost::unit_test::callback0<boost::unit_test::ut_detail::unused> const&, boost::unit_test::basic_cstring<char const>)':
TestSqDistApproximant.cpp:(.text._ZN5boost9unit_test14make_test_caseERKNS0_9callback0INS0_9ut_detail6unusedEEENS0_13basic_cstringIKcEE[_ZN5boost9unit_test14make_test_caseERKNS0_9callback0INS0_9ut_detail6unusedEEENS0_13basic_cstringIKcEE]+0x13): undefined reference to `boost::unit_test::ut_detail::normalize_test_case_name(boost::unit_test::basic_cstring<char const>)'
collect2: error: ld returned 1 exit status
math/spfit/tests/CMakeFiles/spfit_tests.dir/build.make:128: die Regel für Ziel „math/spfit/tests/spfit_tests“ scheiterte
make[2]: *** [math/spfit/tests/spfit_tests] Fehler 1
CMakeFiles/Makefile2:527: die Regel für Ziel „math/spfit/tests/CMakeFiles/spfit_tests.dir/all“ scheiterte
make[1]: *** [math/spfit/tests/CMakeFiles/spfit_tests.dir/all] Fehler 2
Makefile:160: die Regel für Ziel „all“ scheiterte

```

**Comment by danstender** [comment]
This might not work everywhere. However, the build break appears late in the test,
maybe the binaries ./scantailor and ./scantailor are already working.

DS

On 01.10.2015 00:34, Wikinaut wrote:
> I did so, but get the same message.
> 
> make clean
> cmake .
> make
> 
> ```
> [ 93%] Linking CXX executable spfit_tests
> CMakeFiles/spfit_tests.dir/TestSqDistApproximant.cpp.o: In function `boost::unit_test::make_test_case(boost::unit_test::callback0<boost::unit_test::ut_detail::unused> const&, boost::unit_test::basic_cstring<char const>)':
> TestSqDistApproximant.cpp:(.text._ZN5boost9unit_test14make_test_caseERKNS0_9callback0INS0_9ut_detail6unusedEEENS0_13basic_cstringIKcEE[_ZN5boost9unit_test14make_test_caseERKNS0_9callback0INS0_9ut_detail6unusedEEENS0_13basic_cstringIKcEE]+0x13): undefined reference to `boost::unit_test::ut_detail::normalize_test_case_name(boost::unit_test::basic_cstring<char const>)'
> collect2: error: ld returned 1 exit status
> math/spfit/tests/CMakeFiles/spfit_tests.dir/build.make:128: die Regel für Ziel „math/spfit/tests/spfit_tests“ scheiterte
> make[2]: *** [math/spfit/tests/spfit_tests] Fehler 1
> CMakeFiles/Makefile2:527: die Regel für Ziel „math/spfit/tests/CMakeFiles/spfit_tests.dir/all“ scheiterte
> make[1]: *** [math/spfit/tests/CMakeFiles/spfit_tests.dir/all] Fehler 2
> Makefile:160: die Regel für Ziel „all“ scheiterte

-- 
4096R/DF5182C8
46CB 1CA8 9EA3 B743 7676 1DB9 15E0 9AF4 DF51 82C8
LPI certified Linux admin (LPI000329859 64mz6f7kt4)
http://www.danielstender.com/blog/

**Comment by Wikinaut** [comment]
@danstender You are right, the missing reference concerns the test suite only. ```sudo make install``` also fails, but the binary is working. 

Thanks.

**Comment by danstender** [comment]
All right! :-)
