### ISSUE TITLE
swap page pair orderings?

### ISSUE THREAD

**Issue by jm3** [scantailor/scantailor#173]
is there any way in ScanTailor (or with some related utility) to swap the page orderings if the book scanner's cameras were reversed? (instead of *1:2, 3:4, 5:6*, i have: *2:1, 4:3, 6:5*)

**Comment by Tiesenhausen** [comment]
Here's a way to do it: if ScanTailor produces output with each page
separately, with the left page identified by the letter L and the right
page by R.

Select and copy all the pages with L into a separate folder, and those with
R into another folder.

In the one folder, use Bulk Renamer Utility or a similar program to change
all the L's to R's, and in the other folder change all the R's to L's.

Move all the output pages back into a single folder, and make the pdf from
that.

**Comment by jm3** [comment]
Hi @Tiesenhausen, thanks for the suggestion, but there is no `L` or `R` notation in any of the generated filenames from ScanTailor. Does your version of ScanTailor use different file-naming?

My output looks like: 

    img00011.jbig2                                                                                   
    img00011.tif
    img00011.txt
    img00012.hocr
    img00012.jbig2
    img00012.tif
    img00012.txt
    img00013.hocr
    img00013.jbig2
    img00013.tif
    img00013.txt

I have the ScanTailor for Mac binary, which has a confusing version scheme: the About window says, "Scan Tailor Featured, 2013-04-30".

**Comment by jm3** [comment]
I just did it in ruby — here was my solution: https://gist.github.com/jm3/83a10b9495eaedb68959

**Comment by Tiesenhausen** [comment]
Hi @ Manoogian, I'm using ST 0.9.11.1 for Windows 64 bit. If the program
gets 1.jpg, 2.jpg, 3.jpg, with each jpg a two page spread, it produces
something like 1_L.tif, 1_R.tif, 2_L.tif, as output. Wish I had an example
to check for the exact filenames, but I usually delete these after the
final pdf is produced.
