### ISSUE TITLE
problems with GCC 6

### ISSUE THREAD

**Issue by danstender** [scantailor/scantailor#193]
Hi Nate,

it has been reported that Scantailor is running into problems with GCC 6:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=811871

Greetings,
Daniel Stender

**Comment by tfmorris** [comment]
The same thing happens when attempting to compile on OS X.

The Debian bug report from above is:

```
> sbuild (Debian sbuild) 0.67.0 (26 Dec 2015) on dl580gen9-02.hlinux
...
> /<<PKGBUILDDIR>>/filters/page_split/PageLayoutEstimator.cpp: In static member function 'static page_split::PageLayout page_split::PageLayoutEstimator::cutAtWhitespaceDeskewed150(page_split::LayoutType, int, const imageproc::BinaryImage&, bool, bool, DebugImages*)':
> /<<PKGBUILDDIR>>/filters/page_split/PageLayoutEstimator.cpp:526:74: error: no matching function for call to 'bind(<unresolved overloaded function type>, boost::lambda::lambda_functor<boost::lambda::identity<std::deque<Span>&> >, boost::lambda::placeholder1_type&)'
>   span_finder.find(hist, bind(&std::deque<Span>::push_back, var(spans), _1));
>                                                                           ^
> 
> In file included from /usr/include/boost/lambda/bind.hpp:17:0,
>                  from /<<PKGBUILDDIR>>/filters/page_split/PageLayoutEstimator.cpp:53:
> /usr/include/boost/lambda/detail/bind_functions.hpp:49:1: note: candidate: template<class Result> const boost::lambda::lambda_functor<boost::lambda::lambda_functor_base<boost::lambda::action<1, boost::lambda::function_action<1, T> >, typename boost::lambda::detail::bind_tuple_mapper<Result (&)()>::type> > boost::lambda::bind(Result (&)())
>  bind(Result(& a1)()) {
>  ^~~~
> 
> /usr/include/boost/lambda/detail/bind_functions.hpp:49:1: note:   template argument deduction/substitution failed:
> /<<PKGBUILDDIR>>/filters/page_split/PageLayoutEstimator.cpp:526:74: note:   mismatched types 'Result()' and 'void (std::deque<Span>::*)(std::deque<Span>::value_type&&) {aka void (std::deque<Span>::*)(Span&&)}'
>   span_finder.find(hist, bind(&std::deque<Span>::push_back, var(spans), _1));
```

The error from OS X is 

```
[ 64%] Building CXX object filters/page_split/CMakeFiles/page_split.dir/PageLayoutEstimator.cpp.o
/Users/tfmorris/git/scantailor/filters/page_split/PageLayoutEstimator.cpp:526:25: error: 
      no matching function for call to 'bind'
        span_finder.find(hist, boost::lambda::bind(&std::deque<Span>::pu...
                               ^~~~~~~~~~~~~~~~~~~
/opt/local/include/boost/lambda/detail/bind_functions.hpp:333:1: note: 
      candidate template ignored: couldn't infer template argument 'Result'
bind(Result(&a1)(Par1, Par2), const Arg2& a2, const Arg3& a3) {
...
```

One significant change for GCC 6 from https://gcc.gnu.org/gcc-6/changes.html is that they switched the default mode to `std=g++14` so I suspect this is a C++ standard version compatibility issue.

**Comment by bromeliad** [comment]
I've submitted [pull request 209](https://github.com/scantailor/scantailor/pull/209) to fix this.  In C++11 there's a new overload for push_back so it's sometimes necessary to specify which is the correct overload, and there's a namespace conflict between std::bind and boost::lambda::bind.

**Comment by ncraun** [comment]
I've merged in bromeliad's pull request, so I think this fixes the problem.

**Comment by tfmorris** [comment]
As I commented on the PR, it fixed it for me on OS X. Thanks for merging.

It'd be great to have a release that incorporates the fix so that downstream packages will pick it up (e.g. MacPorts which is currently broken)

**Comment by ncraun** [comment]
The fix is included in version 0.9.12.1: https://github.com/scantailor/scantailor/releases/tag/RELEASE_0_9_12_1

I'm not sure about MacPorts, but @ilovezfs is working on an updated Homebrew release with this version.

**Comment by tfmorris** [comment]
Thanks! I'll open a ticket for the MacPorts maintainer.

**Comment by ilovezfs** [comment]
@ncraun https://github.com/Homebrew/homebrew-x11/pull/205

I labeled it 0.9.12 because on OS X there doesn't seem to be a way to determine it's 0.9.12.1. Is there a possibility that, for example, 0.9.12.2 would ever exist, or would you just create 0.9.13 in that case?

**Comment by tfmorris** [comment]
The portfile has been updated:
https://trac.macports.org/browser/trunk/dports/graphics/scantailor/Portfile

Not sure how long it'll take to propagate. They also update the old links
to sourceforge that they still had.

**Comment by atla5** [comment]
can we close this? just double checking.

**Comment by bromeliad** [comment]
Closing it is fine by me, the current Debian maintainer and successor to Daniel Stender.  It's now compiling successfully on Debian with gcc6.
