### ISSUE TITLE
Enh: Ignore a page during output pages size calculation

### ISSUE THREAD

**Issue by trufanov-nok** [scantailor/scantailor#200]
I'm scanning a book and would like to use its cover as a first page. It would be great to have both cover and book's spine in it but addition of spine increases page width and (as cover is most likely the biggest page of the book) affects widths of all pages in project.
I would like to have a way to mark such page to ignore its size while output page sizes calculation. Or even had a way to enter this size manually.

**Comment by Tiesenhausen** [comment]
If you uncheck the box "Match size with other pages" on the Margins page,
the page so marked will be ignored in setting the size of all other pages.

Tiesenhausen

**Comment by trufanov-nok** [comment]
You're right! I've missed this option. Thanks!
