### ISSUE TITLE
New version tag

### ISSUE THREAD

**Issue by ilovezfs** [scantailor/scantailor#204]
Do you mind tagging a new version here so that there will be a new tar file? (https://github.com/scantailor/scantailor/releases)

The current Homebrew formula has to do quite a bit of patching in both the :stable and :devel specs, including for the boost issue, which has to be done in the formula because the upstream patch in https://github.com/scantailor/scantailor/pull/194 doesn't apply cleanly. We'd prefer not to boneyard the formula especially when the issue has been addressed in upstream HEAD, but our :stable specs typically only build from tagged releases, which has led to an unusual amount of patching in the  scantailor formula just to keep the build from failing.

Thanks!

**Comment by ilovezfs** [comment]
FYI: https://github.com/Homebrew/homebrew-x11/pull/197#issuecomment-207373759

**Comment by ncraun** [comment]
I just tagged a new version 0.9.12 with all the fixes from 0.9.11.1 to present. Hope this helps you with the homebrew formula.

https://github.com/scantailor/scantailor/releases/tag/RELEASE_0_9_12

**Comment by bromeliad** [comment]
The [version.h](https://github.com/scantailor/scantailor/blob/master/version.h) file hasn't been updated so the program shows incorrect version numbers.

**Comment by ncraun** [comment]
Thanks, version.h has been updated.

**Comment by ilovezfs** [comment]
Thanks @ncraun I'll try pulling that tag in.

**Comment by ncraun** [comment]
Hi, make sure to pull in version 0.9.12.1 which has the updated version.h: https://github.com/scantailor/scantailor/releases/tag/RELEASE_0_9_12_2

**Comment by ilovezfs** [comment]
Perfect, thank you.

**Comment by ilovezfs** [comment]
@ncraun It's now merged: https://github.com/Homebrew/homebrew-x11/commit/962cafa036867a993e0d7da4dcc3e4f828cd9e61
