### ISSUE TITLE
Windows installer not found on wiki

### ISSUE THREAD

**Issue by moracabanas** [scantailor/scantailor#208]
Hi, program is excellent. Just wondering why there is not any link to donwload windows installer from wiki [here](https://github.com/scantailor/scantailor/wiki/User-Guide), where it says "Versions for Windows come in the form of an installer. Install the program and run through the self-explanatory menu.".

**Comment by ncraun** [comment]
Thanks for pointing this out, I've added links to download the installer to the wiki page.
