### ISSUE TITLE
README file

### ISSUE THREAD

**Issue by leoheck** [scantailor/scantailor#213]
Hi, it is possible to add a README.md file describing what is necessary to compile and how to compile it? I can start one if you want.

**Comment by bakroistvan** [comment]
+1

**Comment by atla5** [comment]
most all of the information that would be put there is already in the wiki.

**Comment by leoheck** [comment]
Oh, I didn't know about the wiki. An README.md file referring to the wiki would be nice. Thank you for the answere.

**Comment by atla5** [comment]
@ncraun: I just created a README.md for the project by compiling information on the wiki and main site. 
[Pull  request 218](https://github.com/scantailor/scantailor/pull/218).

**Comment by ncraun** [comment]
Thanks @atla5 I've merged it in!
