### ISSUE TITLE
Apply 'Hacktoberfest' label to encourage new developers

### ISSUE THREAD

**Issue by atla5** [scantailor/scantailor#249]
Digital Ocean has an event going on this month called '[Hacktoberfest](https://hacktoberfest.digitalocean.com/)' where if you contribute to a number of projects you get a shirt or something.

Might be a good idea to put on some issue labels for that and 'help wanted'.

**Comment by ncraun** [comment]
Sounds like a good idea to me. But I think we should get the contributing guidelines set up first before encouraging people to contribute for "Hacktoberfest". I think we can use most of the C4 guide as is, but we need to adapt a few things, like the code style and the branch policies if we use something like @ospalh suggested

**Comment by atla5** [comment]
outdated.
