### ISSUE TITLE
Can't install scantailor with Homebrew on MacOS 10.12 and Mac OS 10.13

### ISSUE THREAD

**Issue by davideradice** [scantailor/scantailor#273]
```
brew tap homebrew/boneyard && brew install scantailor
Updating Homebrew...
Error: No available formula with the name "scantailor"
It was migrated from homebrew/x11 to homebrew/boneyard.
You can access it again by running:
  brew tap homebrew/boneyard
```

Here is my conf:

> Mac OS X
> 10.12.4

> Brew
> Homebrew 1.2.1
> Homebrew/homebrew-core (git revision 0054; last commit 2017-05-17)

> Xcode
> Xcode 8.3.2
> Build version 8E2002

> GCC
> Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
> Apple LLVM version 8.1.0 (clang-802.0.42)
> Target: x86_64-apple-darwin16.5.0
> Thread model: posix
> InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by reagle** [comment]
Is there any way to run scantailor on Mac now?

**Comment by th122** [comment]
The entire boneyard has been deprecated and emptied. The formulae can be checked out using the old revision:
'git clone https://github.com/Homebrew/homebrew-boneyard'
'cd homebrew-boneyard'
'git checkout f0f4e12197'

**Comment by NickBarreto** [comment]
I did get scantailor to install using the above git commands, but I also had to edit `homebrew-boneyard/scantailor.rb` a little.

In that file it says `depends_on "qt"`, which if you leave as is homebrew will install qt5 which won't work for scantailor and cmake will fail.

I found it most reliable to install qt4 first, directly. To do that, as per https://github.com/cartr/homebrew-qt4, run:

```
brew tap cartr/qt4
brew tap-pin cartr/qt4
brew install qt@4
```

Now you need to edit `homebrew-boneyard/scantailor.rb`. You need to change the line that said  `depends_on "qt"` to use the old tap.:

```
  depends_on "cartr/qt4/qt@4"
```

Once you have saved that change, then you can run, from that directory

```
$ brew install scantailor.rb
```

(You may get an error where it tells you to install xquartz. You can to that with `brew cask install xquartz`.)

Scantailor should install and you can run it from the terminal with 

```
$ scantailor
```

**Comment by davideradice** [comment]
Dear NickBarreto, I've followed your instructions on Mac OS 10.13 and had no problems at all during the installation. After I run 'scantailor' I've got this error:

`dyld: Library not loaded: /usr/local/opt/jpeg/lib/libjpeg.9.dylib
  Referenced from: /usr/local/opt/libtiff/lib/libtiff.5.dylib
  Reason: image not found
[1]    49088 abort      scantailor`

My stack now:

> Mac OS X
> 10.13
> 
> Brew
> Homebrew 1.3.6
> Homebrew/homebrew-core (git revision 35672; last commit 2017-10-30)
> 
> Xcode
> Xcode 9.0.1
> Build version 9A1004
> 
> GCC
> Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
> Apple LLVM version 9.0.0 (clang-900.0.38)
> Target: x86_64-apple-darwin17.0.0
> Thread model: posix
> InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by NickBarreto** [comment]
Hi @davideradice, do you have libtiff installed correctly? I ran through these steps on a brand new install last week as well as on my main machine before I wrote those instructions and didn't have this issue, so I'm not sure what the problem is.

If I run `brew info libtiff` I see `libtiff: stable 4.0.8 (bottled)`. Maybe try and run `brew doctor` and see if there are any problems? Or perhaps try `brew upgrade libtiff`?

**Comment by davideradice** [comment]
Dear NickBarreto,

libtiff is installed and can't be upgraded. See down for details. I think that the problem is related to the version of jpeg?

Now it looks for 8 and I have 9:

With
`brew install jpeg`
I have:
```
Updating Homebrew...
==> Downloading https://homebrew.bintray.com/bottles/jpeg-9b.high_sierra.bottle.tar.gz
Already downloaded: /Users/davide/Library/Caches/Homebrew/jpeg-9b.high_sierra.bottle.tar.gz
==> Pouring jpeg-9b.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/jpeg/9b: 20 files, 723.9KB
```
and `$ scantailor 
gives me:
```
dyld: Library not loaded: /usr/local/opt/jpeg/lib/libjpeg.8.dylib
  Referenced from: /usr/local/bin/scantailor
  Reason: image not found
[1]    25747 abort      scantailor
```

Here is the output for the suggestions you gave me:

```
brew info libtiff
libtiff: stable 4.0.8 (bottled)
TIFF library and utilities
http://libtiff.maptools.org/
/usr/local/Cellar/libtiff/4.0.8_5 (245 files, 3.4MB) *
  Poured from bottle on 2017-10-30 at 17:40:08
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/libtiff.rb
==> Dependencies
Required: jpeg ✔
Optional: xz ✔
==> Options
--c++11
	Build using C++11 mode
--with-xz
	Include support for LZMA compression
```

```
brew upgrade libtiff
Updating Homebrew...
...
Error: libtiff 4.0.8_5 already installed
```

```
brew doctor
Your system is ready to brew.
```

**Comment by cbertelli** [comment]
I followed these instructions on 10.9 but I choose qt-4 by OsGeo4Mac and I unexpectedly got a native Scantailor (no X11). Thanks

**Comment by johnpilbeam** [comment]
Based on the discussion above, the following steps definitely work on macOS 10.12.6 (Sierra).

```
git clone https://github.com/Homebrew/homebrew-boneyard
cd homebrew-boneyard
git checkout f0f4e12197
```

Edit homebrew-boneyard/scantailor.rb and change the line:
`depends_on "qt"`
 to:
`depends_on "cartr/qt4/qt@4"`
Save file.

```
brew tap cartr/qt4
brew tap-pin cartr/qt4
brew install qt@4
brew install scantailor.rb
```

Run Scantailor:
`scantailor`

**Comment by ylluminate** [comment]
@davideradice @reagle MacPorts `scantailor` works great still.

**Comment by senderle** [comment]
Is there a reason the solution from @johnpilbeam can't be updated to a working brew formula and placed in a [tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md)?

**Comment by ylluminate** [comment]
I don't know if it's worth maintaining taps. Personally I'm moving away from Homebrew because I've gotten to the point where I'm tired of hunting for taps and going down this externalized route. When I want packages, I want to find them in a central repository and thus I'm, sadly, finding MacPorts now greatly superior to the Homebrew methodology.

I was able to simply `sudo port install scantailor` and then `open /Applications/MacPorts/ScanTailor.app` (or run from the shell, `scantailor <args>`).  

This is a greatly simplified solution compared to what is required now by Homebrew.  Presently I'm running both Homebrew and MacPorts with no problem, but I'm migrating towards MacPorts due to it's (now realized) cleaner and more robust nature.  I don't want to start a package manager war, but I am surprised and pleased to not have to deal with the ever growing issues I've been having with Homebrew packages.

**Comment by senderle** [comment]
I don't want to start a war either, lol! But for better or worse, not maintaining a tap does limit the accessibility of scantailor to people who are used to homebrew. As it stands, it's a choice between installing MacPorts, going through the elaborate process described above, or just giving up. Starting a tap would make that a choice between installing MacPorts and installing a new tap.

I'll look into setting one up myself, and I'll post here if I can get it working.

**Comment by johnpilbeam** [comment]
I'm definitely in favour of setting up a tap for this. I used to use MacPorts, but moved to Homebrew as, at the time, it seemed to be more reliable, but I agree with @senderle having a tap would increase the usage of scantailor.

**Comment by gingerbeardman** [comment]
@johnpilbeam comment on 16 Jan 2018: worked for me!

**Comment by reagle** [comment]
The suggestion from [Jan 16, 2018](https://github.com/scantailor/scantailor/issues/273#issuecomment-357964331) no longer works because boneyard is gone. Any other suggestions?

**Comment by cbertelli** [comment]
Qt4 is still available in the OsGeo/OsGeo4Mac repository. You may still use that.

**Comment by reagle** [comment]
I don't understand the particulars and would welcome specific steps.

**Comment by cbertelli** [comment]
Please, have a look at:
https://github.com/OSGeo/homebrew-osgeo4mac/
you will find the remaining Qt4 packages for homebrew.

**Comment by reagle** [comment]
But I can't even access the recipe for scantailor as the boneyard is gone.

**Comment by cbertelli** [comment]
what about
https://github.com/yb85/scantailor-advanced-osx
?

**Comment by reagle** [comment]
@cbertelli thanks for that link to @yb85, it does build!
