### ISSUE TITLE
[SOLVED] how to create pdf from scantailor output files?

### ISSUE THREAD

**Issue by omega3** [scantailor/scantailor#308]
What program do you use on Linux to create pdf after scantailor processing? Scantailor produced tif files. I wanted to use img2pdf to create pdf from it but it fails: 

```
img2pdf --output out.pdf *.tif
WARNING:root:Image contains transparency which cannot be retained in PDF.
WARNING:root:img2pdf will not perform a lossy operation.
WARNING:root:You can remove the alpha channel using imagemagick:
WARNING:root:  $ convert input.png -background white -alpha remove -alpha off output.png
ERROR:root:error: Refusing to work on images with alpha channel
```

What can I do about it?

If scantailor is still developed it would be great to have options save as pdf (to save all changes made to pdf).

**Comment by FriedrichFroebel** [comment]
You may choose to use ImageMagick for combining the TIFF files to a PDF file directly. To get smaller files I personally prefer exporting the TIFFs to a DJVU file using `didjvu` and then running `ocrodjvu` for some OCR text afterwards.

**Comment by omega3** [comment]
Somewhere on Internet I read: 

> Use img2pdf, not ImageMagick. ImageMagick decodes the JPEG, resulting in generation loss and is 10–100 times slower than img2pdf.

As I prepare this for OCR I would prefer not to loose quality.

I wonder why these scantailor output files "contains transparency" and  "alpha channel". What scantailor option does that? Did I do something wrong when using scantailor?

**Comment by jroedel** [comment]
I use tesseract and it's worked amazing for me. I've produced thousands of PDFs worth of scientific articles for research. 
The new major revision of tesseract came out recently and you can probably install it through package managers in Linux (at least Ubuntu repositories are up to date.

I use this command in my `out` folder:
```
ls -1Nv *.tif > filelist.txt && tesseract -l eng+spa filelist.txt article-name pdf
```

**Comment by ncraun** [comment]
I used to use `pdfbeads` when I was scanning, but I haven't had to scan in a long time now, so I don't know if that is the best option nowadays. Here's the process I used to create PDFs back in 2013: https://natecraun.net/articles/linux-guide-to-book-scanning.html#pdf

**Comment by omega3** [comment]
@jroedel
```
> ls -1Nv *.tif > filelist.txt && tesseract -l eng+spa filelist.txt article-name pdf
> ```

This produced OCR-ed pdf file but how can I get rid of this warnings about resolution:

```
ls -1Nv *.tif > filelist.txt && tesseract -l eng+spa filelist.txt article-name pdf
Error opening data file /usr/share/tessdata/spa.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'spa'
Tesseract Open Source OCR Engine v4.0.0 with Leptonica
Page 0 : 02.tif
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 701
Page 1 : 03.tif
Warning: Invalid resolution 0 dpi. Using 70 instead.

Estimating resolution as 702

```

I also had them when I did:

```
tesseract 02.tif out -l eng
Tesseract Open Source OCR Engine v4.0.0 with Leptonica
Page 1
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 701
```


Maybe I should not use .tif in the first place? But scantailor author recommends it:
https://github.com/scantailor/scantailor/wiki/Tips-for-Scanning

I did:
`convert input.tif -background white -alpha remove -alpha off output.tif`
but it shows
`convert: Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/996.
`
but such output.tif is not suitable for ocr. I tried  OCR of this in pdfexchange editor but it failed. 

I have additional questions about processing pdf on Linux.

1. How can I check what graphic files are in pdf files, I mean their original file format (jpg, tif or other) and resolution and other values if it may be important?

2. How can I extract these graphic to have this original files (without any changes in resolution or file format)?

What is the best input format file for scantailor to avoid these warnings about "resolution 0 dpi. Using 70 instead" or "transparency" and "remove the alpha channel"?

**Comment by omega3** [comment]
After the above referenced conversion in XnConvert  tesseract do OCR without any warnings.

This solves my problems. Thank you all of you for help.

**Comment by konos93** [comment]
this is a solution for windows users 
scantailor advanced
djvusmall 0.4.4
abbyfinereader 12 check save format pdf black and  white with ocr 
edit in notepad ++ tables
use handyoutliner to add table with content
use koreader on your e-ink device to read

**Comment by ALTracer** [comment]
> this is a solution for windows users
> abbyfinereader 12
Is proprietary and expensive. How do we wee Windows users bundle TIFFs into PDF without using ABBYY Finereader, Adobe Acrobat DC Pro, Foxit PhantomPDF etc. but with free software?

**Comment by konos93** [comment]
ALTracer
tor
vpn
download
didnt want to offend anyone or anything

**Comment by risacher** [comment]
> I use tesseract and it's worked amazing for me. I've produced thousands of PDFs worth of scientific articles for research.
> The new major revision of tesseract came out recently and you can probably install it through package managers in Linux (at least Ubuntu repositories are up to date.
> 
> I use this command in my `out` folder:
> 
> ```
> ls -1Nv *.tif > filelist.txt && tesseract -l eng+spa filelist.txt article-name pdf
> ```

This command will create a PDF with the pages in the order of the filenames of the original images.  If your source images are in strict order, this is fine, but mine weren't (I had to go back and re-shoot some where the focus or contrast was off)
.  It would be nice if there was some way for ST to output an ordered list of the output .tif files.   I could write a script to generate this from the .scantailor file, but for my use-case it was easier just to hand-edit filelist.txt.

**Comment by risacher** [comment]
I wrote some javascript that parses the .ScanTailor file and generates an ordered list of filenames in the output directory.  This code will almost certainly only work for projects that are 2-up left-right images, which is to say that it works for me. 

You can run the app here: https://codepen.io/risacher/pen/WNxrPPG

**Comment by ant6n** [comment]
On Windows, I'm really struggling with this tif to searchable pdf conversion as well (I'm not using windows voluntarily for scanning, there's just no linux version for the czur, and adding an operating system break in the workflow, moving a bunch of files with a usb stick to another computer, is probably against the spirit of trying to improve work-flows for scanning books).

The tesseract solution is pretty cumbersome  but also doesn't seem to work on windows (tesseract 5.0 ignores a list of input files, individual input files receive the dpi warning). I tired gImageReader, but it doesn't want to output a pdf without fiddling around with scaling, dpi, cutting and compression - so the carefully crafted output of scantailor gets messed up.

Ideally there should be a software which does the ocr and assembles the tif files into a pdf - but then also compresses the tif files inside the pdf lossless, and compresses the color images using jpg. Haven't found something like that yet.
