### ISSUE TITLE
Anti-Aliasing [sf#25]

### ISSUE THREAD

**Issue by sakulstra** [scantailor/scantailor#59]
Submitted by *anonymous on 2010-12-29 20:09:32

\* Letters are converted to b/w. May it be usefull to have an anti-aliasing option which adds grey pixels at inclinated edges?
\* Dewarping would be great.
\* TIFF to DjVu converter...
\* Besides b/w, color/grey and mixed, another option for grey\_without\_color. This is useful when diagrams are on colored background.

Thanks for development\!

**Comment by atla5** [comment]
moving "grey_without_color" to another issue and closing this one.

- TIFF->DejaVu out of scope.
- anti-aliasing out of scope
- dewarping complete
