### ISSUE TITLE
dewarping - correcting distortion in the center  [sf#31]

### ISSUE THREAD

**Issue by sakulstra** [scantailor/scantailor#66]
Submitted by *anonymous on 2011-05-22 05:42:05

### original 

деворпинг - исправление искажений по центру

Существующая реализация позволяет исправлять в основном "фотографические" искажения, подразумевающие правильную геометрию в центре. Хотелось бы иметь возможность исправлять и "загибы" сканирования.

### translated 

The current implementation allows you to fix mostly "photographic" distortions, implying correct geometry in the center. I would like to be able to correct and the "bends" scanning.

**Comment by atla5** [comment]
poor translation, but i'm pretty sure this is covered in another issue as well.
